version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./assets:/web/assets
      - ./index.html:/web/index.html
      - ./package.json:/web/package.json
      - ./Makefile:/web/Makefile
