steps:
  - commands:
      # Install Pulumi and log into Pulumi Cloud.
      - export PATH="\$HOME/.pulumi/bin:\$PATH"
      - export PULUMI_ACCESS_TOKEN="$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)"

      # Install app deps and build.
      - npm install && npm install --workspaces
      - npm run build

      # Run the tests.
      - npm run test -w chris

      # Run Pulumi.
      - npm run $([ "$BUILDKITE_BRANCH" == "main" ] && echo "deploy" || echo "preview"):production -w chris.infra
