#!/usr/bin/env bash

set -euo pipefail

# export PATH="/.pulumi/bin:$PATH" # Does this ever do anything? Suspect not.
# export PATH="/root/.pulumi/bin:$PATH"
# export PATH="/root/.local/bin:$PATH"
# eval "$(mise activate bash)"
eval "$(/root/.local/bin/mise activate bash)"
# echo "eval \"\$(/root/.local/bin/mise activate bash)\"" >> ~/.bashrc
export PULUMI_ACCESS_TOKEN="$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)"
