#!/usr/bin/env bash

set -euo pipefail

# export PATH="/.pulumi/bin:$PATH" # Does this ever do anything? Suspect not.
# export PATH="/root/.pulumi/bin:$PATH"
export PULUMI_ACCESS_TOKEN="$(buildkite-agent secret get PULUMI_ACCESS_TOKEN)"
