#!/usr/bin/env bash

set -euo pipefail

# This works, but then you have to run it ever time, which makes the initial
# pipeline-upload step unnecessarily slow. So

# echo "Installing Mise..."
export MISE_INSTALL_PATH="/usr/bin/mise"
curl https://mise.run | sh

# echo "Installing Mise-managed tooling..."
mise install

export PATH="$(mise where node)/bin:$PATH"
which node
node -v
