#!/usr/bin/env bash

set -euo pipefail

# This works, but then you have to run it ever time, which makes the initial
# pipeline-upload step unnecessarily slow. So

# echo "Installing Mise..."
curl https://mise.run | sh -s -- --yes --prefix ./tools/mise
export PATH="$PWD/tools/mise/bin:$PATH"

# echo "Installing Mise-managed tooling..."
mise install

export PATH="$(mise where node)/bin:$PATH"
which node
node -v
